// src/client/App.tsx
import AdminPage from './pages/AdminPage';
import './App.css';

export default function App() {
  return (
    <div className="app">
      <header className="app-header">
        <img src="/logo.png" alt="OpenClaw Worker" className="header-logo" />
        <h1>OpenClaw Admin</h1>
      </header>
      <main className="app-main">
        <AdminPage />
      </main>
    </div>
  );
}

// src/client/App.vue
<script setup lang="ts">
import AdminPage from './pages/AdminPage.vue';
</script>

<template>
  <div class="app">
    <header class="app-header">
      <img src="/logo.png" alt="OpenClaw Worker" class="header-logo" />
      <h1>OpenClaw Admin</h1>
    </header>
    <main class="app-main">
      <AdminPage />
    </main>
  </div>
</template>

<style src="./App.css"></style>
